---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "CloudLab"
subtitle: "kerb's"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: dark
colors:
  light:
    highlight-primary: "#dc8a78"
    highlight-secondary: "#dd7878"
    highlight-hover: "#dd7878"
    background: "#eff1f5"
    card-background: "#ccd0da"
    text: "#4c4f69"
    text-header: "#4c4f69"
    text-title: "#8839ef"
    text-subtitle: "#ea76cb"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#179299"
    link-hover: "#40a02b"
  dark:
    highlight-primary: "#f5e0dc"
    highlight-secondary: "#f2cdcd"
    highlight-hover: "#f2cdcd"
    background: "#1e1e2e"
    card-background: "#313244"
    text: "#cdd6f4"
    text-header: "#cdd6f4"
    text-title: "#cba6f7"
    text-subtitle: "#f5c2e7"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#94e2d5"
    link-hover: "#a6e3a1"

# Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/kerbaras/cloudlab"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://github.com/kerbaras/cloudlab/wiki"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "ArgoCd"
        logo: "https://avatars.githubusercontent.com/u/30269780?s=200&v=4"
        subtitle: "GitOps Application Delivery"
        tag: "app"
        keywords: "gitops kubernetes"
        url: "https://argocd.kerbaras.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Portainer"
        logo: "https://avatars.githubusercontent.com/u/22225832?s=200&v=4"
        subtitle: "Kubernetes Management"
        tag: "app"
        url: "#"
