---
title: CloudLab
subtitle: "Kerb's"
logo: logo.png

header: true
footer: '<p>Created with <span class=has-text-danger>❤️</span> with <a href=https://bulma.io/>bulma</a>, <a href=https://vuejs.org/>vuejs</a> & <a href=https://fontawesome.com/>font awesome</a> // Fork me on <a href=https://github.com/bastienwirtz/homer><i class=fab fa-github-alt></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: dark
colors:
  light:
    highlight-primary: "#1e1e2e"
    highlight-secondary: "#ccd0da"
    highlight-hover: "#ccd0da"
    background: "#eff1f5"
    card-background: "#ccd0da"
    text: "#4c4f69"
    text-header: "#4c4f69"
    text-title: "#4c4f69"
    text-subtitle: "#8839ef"
    card-shadow: "rgba(0, 0, 0, 0.1)"
    link: "#8839ef"
    link-hover: "#8839ef"
  dark:
    highlight-primary: "#1e1e2e"
    highlight-secondary: "#313244"
    highlight-hover: "#313244"
    background: "#1e1e2e"
    card-background: "#313244"
    text: "#cdd6f4"
    text-header: "#cdd6f4"
    text-title: "#cdd6f4"
    text-subtitle: "#cba6f7"
    card-shadow: "rgba(0, 0, 0, 0.4)"
    link: "#cba6f7"
    link-hover: "#cba6f7"

links:
  - name: Contribute
    icon: fab fa-github
    url: https://github.com/kerbaras/cloudlab
    target: _blank # optional html a tag target attribute
  - name: Wiki
    icon: fas fa-book
    url: https://github.com/kerbaras/cloudlab/wiki
    target: _blank # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a items key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:

  - name: Management
    icon: fas fa-power-off
    items:
      - name: ArgoCD
        logo: https://avatars.githubusercontent.com/u/30269780?s=200&v=4
        url: https://argocd.kerbaras.com
        target: _blank
        keywords: gitops kubernetes argo cd ci
        tag: ci/cd
      - name: Portainer
        logo: https://avatars.githubusercontent.com/u/22225832?s=200&v=4
        tag: infra
        url: "#"
      - name: Proxmox
        logo: https://avatars.githubusercontent.com/u/2678585?s=200&v=4
        subtitle: Comming Soon
        url: "#"
        tag: infra
      - name: TrueNAS
        logo: https://avatars.githubusercontent.com/u/53482242?s=200&v=4
        subtitle: Comming Soon
        url: "#"
        tag: storage

  - name: Monitoring
    icon: fas fa-heartbeat
    items:
      - name: Grafana
        logo: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg
        url: "#"
        tag: metrics
      - name: Kibana
        icon: fa-solid fa-chart-bar
        url: "#"
        tag: logs

  - name: Services
    icon: fas fa-cloud
    items:
      - name: Zitadel
        icon: fas fa-fingerprint
        subtitle: SSO Authentication
        url: https://accounts.kerbaras.com/
        tag: accounts
      - name: AWS Console
        icon: fa-brands fa-aws
        subtitle: Amazon Web Services
        url: http://console.aws.amazon.com/console/home
        tag: provider
        target: _blank
      - name: Hetzner
        icon: fas fa-server
        url: https://robot.hetzner.com/server
        tag: provider
        target: _blank

  - name: Apps
    icon: fa-solid fa-rocket
    items:
      - name: Redash
        logo: https://avatars.githubusercontent.com/u/10746780?s=200&v=4
        url: "#"
      - name: Ansible Semaphore
        icon: fa-solid fa-wand-magic-sparkles
        subtitle: Comming Soon
        url: "#"
      - name: Argo Workflows
        icon: fa-solid fa-list-check
        subtitle: Comming Soon
        url: "#"
