apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sources.yaml
  - vm-stack.yaml
  - victoria-logs.yaml
  - loki-vl-proxy.yaml
  - alloy.yaml
  - referencegrant-envoy-otlp.yaml
  - httproute.yaml
  - policies
