apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ../../base
  - gateway.yaml

patches:
  - path: theme.yaml

configMapGenerator:
  - name: homer-assets
    files:
      - ./assets/config.yml
      - ./assets/catppuccin-mocha.css
      # - logo.svg=./assets/logo.svg
