apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  template:
    spec:
      volumes:
      - name: assets
        configMap:
          name: homer-assets
          items:
          - key: config.yml
            path: config.yml
          - key: catppuccin-mocha.css
            path: catppuccin-mocha.css
