# OCI helm registry registration for the Envoy Gateway chart.
apiVersion: v1
kind: Secret
metadata:
  name: repo-envoy-gateway-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: envoy-gateway-oci
  type: helm
  url: registry-1.docker.io/envoyproxy
  enableOCI: "true"
