# zot credentials: the htpasswd file (bcrypt), mounted at /secret.
apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: zot
stringData:
    htpasswd: ENC[AES256_GCM,data:Zue7zRwMziHEPsQokSC5t1kYzIV8cyXhWbCxU7a4utA85dyldbCguCE3NmMoyEnuJ7J/L/0tFltT5EmsOa9pAIaB,iv:r5Fe+8jUJ7M04UVFIvdAPmoT8t3J57AikTuOwhvqBVY=,tag:3c9rSuDfeQ2CtJ+/xZgWdw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:203447569320:key/99cadca6-ba46-4ef0-9df2-9f2678b7962e
          created_at: "2026-07-13T20:53:09Z"
          enc: AQICAHghjr0dewq1sbS0xUAI2yzWINRSDNS1+gWClJ5Dzg9INgE+QzqSVpbe2BkQ97KikgX8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOUjM/VI5tcO6BQMhAgEQgDt9atGjG0QoNw2ptQEQEQ9na8rz2zVBT6WoFcfRJCRpYktvljL5koflUOwZjNm6ChBoT0u/Snr48WPcaA==
          aws_profile: ""
    lastmodified: "2026-07-13T20:53:10Z"
    mac: ENC[AES256_GCM,data:0ofPfpsLvGwk7yU2SeN47HJpH1Gd8urKlDyTo0KLBAit9R7lVDCopyz64I5xWkysF+CWhvFifA4V1lK96pn89aKG9tsfhz5PJztIlDJOAWqQ1wGnMo0rfmDsfwCtagg7dfhe/YwaXLkzPlzKicyPpyrXwyn3+R0+3AYqZHKo+do=,iv:iqDJL2ga2wrN6++wmN1u1/+v28Z2Lwrn9FiQ//+dkvk=,tag:W2WJzFqOFkLvAGqDykCZnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
