# zot credentials, mounted at /secret: the htpasswd file (bcrypt) and the
# Zitadel "zot" web app credentials for the openid provider (credentialsFile).
apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: zot
stringData:
    htpasswd: ENC[AES256_GCM,data:mzuK5PZ7UVp4EMHx7S9bfM8MHKzhSqAzx9YplNz0j60NU1ZFCzhwX47PIzGu7GMDLbPpRZlrwC+QM4N+HcOO0QtJ,iv:zHUDMghaxS/jmr7q81mJY9DIn+aiXP+GwdZWk56X8V0=,tag:lPx3EqIUBbmcNfXK2OO68A==,type:str]
    oidc-credentials.json: ENC[AES256_GCM,data:QTFxsaHCK707AGnWuCyB3iblnCBqSJ6cnsoobBOD8yPOUquGSnB6e8WeK29vP6cdTqzGDDI7LlvzA+Hyw09kwdXcpKConPeBqfzEWhN7HAFWzM34C4RJnm0Ljma5MOYQ8KlAHoTPalzq1fsZ6KYRwoFFEq7dhw==,iv:4Vnujr+ZMIVOemtDOs+YvLdQjZczrtSeRTfHBvS6L5U=,tag:YRt5n7Bn2BAmieh2rYJuXw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:203447569320:key/99cadca6-ba46-4ef0-9df2-9f2678b7962e
          created_at: "2026-07-13T21:28:03Z"
          enc: AQICAHghjr0dewq1sbS0xUAI2yzWINRSDNS1+gWClJ5Dzg9INgHDX0uVptvYSe37krVPbyiLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsjj+knu+lim4I0jXAgEQgDuNvJhx0868NAW7DTh8l9StSzd7dD5cfkAEANRexJziPywM+HylitSs7OOi/f18MF+VjcJGKa6oj3xHGg==
          aws_profile: ""
    lastmodified: "2026-07-13T21:28:04Z"
    mac: ENC[AES256_GCM,data:LhJYMFV8p0F9z24pWSJ8oPlCoC3C9TvrCmf+ITPpSs3ClRTDcNDiAip4YEhdQZFlR74w49FZ2E26uSkN7oJfkIyx8DXjtjRWon330WTBK4NwCjex6mHTMxzhkSRITyeG2zbSBKvvOVjZElZrhe3+tNuYxGzZPIyBxbxPgIFTMjw=,iv:O7U2P8Oix9w1aiKw0gs1RUSNbH3wDbbwbAlMBnoKQmI=,tag:FOGqcmj2TxwY7WXrCCVH3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
