apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer:lastest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - name: assets
            mountPath: /www/assets
      volumes:
      - name: assets
        configMap:
          name: homer-assets
          items:
          - key: config.yml
            path: config.yml
