apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cilium-ks.yaml
  - cert-manager-ks.yaml
  - envoy-gateway-system-ks.yaml
  - edge-ks.yaml
  - openebs-ks.yaml
  - kyverno-ks.yaml
  - identity-ks.yaml
