apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - lb-pools.yaml
  - envoyproxy.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - redirect.yaml
  - cert-issuer.yaml
  - certificate.yaml
