apiVersion: ENC[AES256_GCM,data:IuQ=,iv:pSxGC/jcgLPWOsXPBit2qBPseWM78zDSyejB3RFO7pQ=,tag:pMzr1w1DqmaauHPwamw9IA==,type:str]
kind: ENC[AES256_GCM,data:AODWB1JA,iv:S7d0q2r/pVQuqPnzUy+VmsmRydnzeRswc0gGkrjKAK8=,tag:twLd0RhyVFakUfJwAbPjrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yzur92+GKrBtXtz3tw28xx/HOQ==,iv:LjMsizwlhk5bS0plewxvH0m9ATXJb50HXAz3PVKyxKc=,tag:w+i97S2yqYPElkp0CfU7cA==,type:str]
    namespace: ENC[AES256_GCM,data:Z0HHjnbYTI7ujLmi,iv:vhSu/16aW9kgwsiJFiFdsSWOx0irwGSxOHrgs4EVccA=,tag:PNlBX4IfTSNHQg1DlKQL3g==,type:str]
type: ENC[AES256_GCM,data:N60tW1mA,iv:9K/akAED332JfIhGVJKJ7ncH+0ulXxoB+ehguuRP6sQ=,tag:X9B8VelgUFkWcjtTvzlGLw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:wyUi+OEUGcAHpFWPz5G58HRwZwE=,iv:cfKDR10xIlvdEKXNTVDVVq7sUOKYLlFAnhv6Yu6uQ4o=,tag:WV5V63RTYKyTdRz2NAA2hA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:4nqGYIJTqG9CMdf5uPIoO3YLnJn7sOAkzDBGJ81Gd8B2mmZHlIRkwA==,iv:I/f/+z3wq7WV/JkbuWTpAsTAFp7vZCvz/yPWglPYzrE=,tag:lKs/kp5G8fsyfQzgDSe7TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVlM0VjIwZEowMStaSFFa
            MXowQUNEUHZQOHNwN2ZveHd3ZE9Fb1EybHdFCktCdFZ6TmJDTy90YWtqOEhNRzUx
            WmFvWEFwd2l0a0RPUVY3WmswczB0cGsKLS0tIHFTV2pBOUQ1VmxQRlhic2RlcEdu
            Z0hzSEJJUzV5RUkxMkt4d2x1Nll0cDQKLtEj+2Eb3LizKbnFnKklPp7YqWWku4H5
            yQajQ4XhzKYL/3Sqq0vs1w5AowU9ck1CE1cbBsvIYrqb+uu0yBbNsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14zk8v7xuur9z93f6yzscdyn35t47547we0yyx8datxrm2hjr2y8qk89nkr
    lastmodified: "2026-07-11T21:55:41Z"
    mac: ENC[AES256_GCM,data:K3P50zNUwf1c1i8qdF7iooqtvlJi69Oko2M1u7B8PM/myZaL6hXEOH7i04okNR3ujVou/3MdP7TK3BK9MNaf4YH7vFgQ84Mi6DD7NA3CsNtTtFCSeMrRuU1L2evRbvCE0SmIM729qIIHnNk/l0Kb8qVAwXHu95CybRw6TXUfXG4=,iv:zF+jo9D+nk6xPlEhMblqbyUV0jom7ZHi8CpjeAd+FHw=,tag:2XR7q4hxnJyLbY+gyon2HA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
