apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portainer
resources:
  - https://downloads.portainer.io/ce2-19/portainer-lb.yaml
  - gateway.yaml

patches:
  - path: service.yaml
  - path: portainer.yaml
